FROM python:3.12

WORKDIR /app

RUN mkdir ./src
RUN mkdir ./src/model

COPY pyproject.toml poetry.lock ./
COPY src/server.py ./src/
COPY src/nyiso.py ./src/
COPY src/model/sunburst_ml.json ./src/model/
COPY src/model/target_scaler.pkl ./src/model/
COPY src/model/train_scaler.pkl ./src/model/

RUN pip install poetry && poetry install --no-root

CMD ["poetry", "run", "uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "80"]
